version: "3.9"

services:
  app:
    build: .
    restart: always
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_HOST=db
      - DB_PORT=3306
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - db
      - redis

  redis:
    image: redis:alpine
    restart: always

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: web2
      MYSQL_USER: web2
      MYSQL_PASSWORD: web2password
    volumes:
      - db-prod-data:/var/lib/mysql

volumes:
  db-prod-data: