<?php

namespace App\Enums;

enum PermissionType: string
{
    // Category
    case VIEW_ALL_CATEGORIES = 'VIEW_ALL_CATEGORIES';
    case RESTORE_CATEGORIES = 'RESTORE_CATEGORIES';
    case CREATE_CATEGORIES = 'CREATE_CATEGORIES';
    case MOVE_CATEGORIES = 'MOVE_CATEGORIES';
    case UPDATE_CATEGORIES = 'UPDATE_CATEGORIES';
    case DELETE_CATEGORIES = 'DELETE_CATEGORIES';

    // Statistical
    case VIEW_STATISTICAL = 'VIEW_STATISTICAL';

    // Product
    case VIEW_PRODUCTS_ADMIN = 'VIEW_PRODUCTS_ADMIN';
    case CREATE_PRODUCT = 'CREATE_PRODUCT';
    case UPDATE_PRODUCT = 'UPDATE_PRODUCT';
    case RESTORE_PRODUCT = 'RESTORE_PRODUCT';
    case DELETE_PRODUCT = 'DELETE_PRODUCT';

    // User
    case VIEW_USERS = 'VIEW_USERS';
    case VIEW_USER_DETAIL = 'VIEW_USER_DETAIL';
    case CREATE_USER = 'CREATE_USER';
    case ASSIGN_ROLE = 'ASSIGN_ROLE';

    case ASSIGN_STATUS = 'ASSIGN_STATUS';

    // Order
    case VIEW_ORDERS_ADMIN = 'VIEW_ORDERS_ADMIN';
    case UPDATE_ORDER_STATUS = 'UPDATE_ORDER_STATUS';

    case VIEW_USER_RANKS = 'VIEW_USER_RANKS';
    case CREATE_USER_RANK = 'CREATE_USER_RANK';
    case UPDATE_USER_RANK = 'UPDATE_USER_RANK';


    // HRM: Schedules
    case VIEW_SCHEDULE_REPORT = 'VIEW_SCHEDULE_REPORT';
    case VIEW_DAILY_SCHEDULE = 'VIEW_DAILY_SCHEDULE';
    case SET_DEFAULT_SCHEDULE = 'SET_DEFAULT_SCHEDULE';
    case ASSIGN_SHIFT = 'ASSIGN_SHIFT';
    case DELETE_SHIFT_ASSIGNMENT = 'DELETE_SHIFT_ASSIGNMENT';

    // HRM: Leave Requests
    case VIEW_LEAVE_LIST = 'VIEW_LEAVE_LIST';
    case APPROVE_LEAVE = 'APPROVE_LEAVE';

    // HRM: Shifts & Holidays
    case CREATE_SHIFT = 'CREATE_SHIFT';
    case UPDATE_SHIFT = 'UPDATE_SHIFT';
    case DELETE_SHIFT = 'DELETE_SHIFT';
    case MANAGE_HOLIDAYS = 'MANAGE_HOLIDAYS';

    // HRM: Career & Position
    case PROMOTE_EMPLOYEE = 'PROMOTE_EMPLOYEE';
    case CREATE_POSITION = 'CREATE_POSITION';
    case UPDATE_POSITION = 'UPDATE_POSITION';
    case DELETE_POSITION = 'DELETE_POSITION';

    // Salary
    case CREATE_SALARY_CONFIG = 'CREATE_SALARY_CONFIG';
    case UPDATE_SALARY_CONFIG = 'UPDATE_SALARY_CONFIG';
    case DELETE_SALARY_CONFIG = 'DELETE_SALARY_CONFIG';
    case MANAGE_SALARY_SCALES = 'MANAGE_SALARY_SCALES';
    case CALCULATE_SALARY = 'CALCULATE_SALARY';

    // RBAC & System
    case MANAGE_ROLES = 'MANAGE_ROLES';
    case MANAGE_PERMISSION_GROUPS = 'MANAGE_PERMISSION_GROUPS';
    case EXPORT_DATA = 'EXPORT_DATA';

    // Voucher Management
    case VIEW_ALL_VOUCHER = 'VIEW_ALL_VOUCHER';
    case CREATE_VOUCHER = 'CREATE_VOUCHER';
    case UPDATE_VOUCHER = 'UPDATE_VOUCHER';
    case DELETE_VOUCHER = 'DELETE_VOUCHER';

    case VIEW_REVIEWS_ADMIN = 'VIEW_REVIEWS_ADMIN';
    case DELETE_REVIEWS_ADMIN = 'DELETE_REVIEWS_ADMIN';

    // Supplier Management
    case VIEW_SUPPLIERS = 'VIEW_SUPPLIERS';
    case ADD_SUPPLIER = 'ADD_SUPPLIER';
    case UPDATE_SUPPLIER = 'UPDATE_SUPPLIER';
    case DELETE_SUPPLIER = 'DELETE_SUPPLIER';


    case VIEW_IMPORT_PRODUCT = 'VIEW_IMPORT_PRODUCT';
    case ADD_IMPORT_PRODUCT = 'ADD_IMPORT_PRODUCT';
    case CONFIRM_IMPORT_PRODUCT = 'CONFIRM_IMPORT_PRODUCT';
    case CANCEL_IMPORT_PRODUCT = 'CANCEL_IMPORT_PRODUCT';
    case UPDATE_IMPORT_PRODUCT = 'UPDATE_IMPORT_PRODUCT';
    case DELETE_IMPORT_PRODUCT = 'DELETE_IMPORT_PRODUCT';

    // --- QUẢN LÝ VAI TRÒ (Roles) ---
    case VIEW_ROLES = 'VIEW_ROLES';
    case CREATE_ROLE = 'CREATE_ROLES';
    case UPDATE_ROLE = 'UPDATE_ROLES';
    case DELETE_ROLE = 'DELETE_ROLE';

    // --- QUẢN LÝ NHÓM QUYỀN (Group Permissions) ---
    case VIEW_PERMISSION_GROUPS = 'VIEW_PERMISSION_GROUPS';
    case CREATE_PERMISSION_GROUP = 'CREATE_PERMISSION_GROUP';
    case UPDATE_PERMISSION_GROUP = 'UPDATE_PERMISSION_GROUP';
    case DELETE_PERMISSION_GROUP = 'DELETE_PERMISSION_GROUP';
}